export const USER = {
  GET_POST:"GET_POST",
  SET_ALL_POST:"SET_ALL_POST",
  SET_CAMERA_CAPTURE_IMAGE:"SET_CAMERA_CAPTURE_IMAGE",
  SET_LOCAL_DUMMY_DATA:"SET_LOCAL_DUMMY_DATA",
  APP_LOADER:"APP_LOADER"
};
